name: Publish

on:
   push:
    branches: [ master ]
   pull_request:
    branches: [ master ]

jobs:
   publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        include-prerelease: true
        
        
    - name: Publish 20Clash Windows x64
      run: dotnet publish /p:Configuration=Release  /p:Platform=x64 /p:PublishProfile=windows_console
      working-directory: ./20Clash/
      
    - name: Publish 20Clash Windows x64
      run: dotnet publish /p:Configuration=Release  /p:Platform=x64 /p:PublishProfile=windows_gui
      working-directory: ./20Clash/
      
    - name: Publish 20Clash Linux x64
      run: dotnet publish /p:Configuration=Release  /p:Platform=x64 /p:PublishProfile=linux_console
      working-directory: ./20Clash/
      
    - name: Publish 20Clash Linux x64
      run: dotnet publish /p:Configuration=Release  /p:Platform=x64 /p:PublishProfile=linux_gui
      working-directory: ./20Clash/
      
    - name: Publish 20Clash Mac x64
      run: dotnet publish /p:Configuration=Release  /p:Platform=x64 /p:PublishProfile=mac_console
      working-directory: ./20Clash/
      
    - name: Publish 20Clash Mac x64
      run: dotnet publish /p:Configuration=Release  /p:Platform=x64 /p:PublishProfile=mac_gui
      working-directory: ./20Clash/
      
    - name: Upload AssetRipperConsole Windows x64
      uses: actions/upload-artifact@v2
      with:
        name: 20Clash_win64
        path: /home/runner/work/20Clash/20Clash/src/ClashofClans.Utilities/bin/Release/*
        if-no-files-found: error
    - name: Upload AssetRipperGUI Windows x64
      uses: actions/upload-artifact@v2
      with:
        name: 20Clash2_win64
        path: /home/runner/work/20Clash/20Clash/src/ClashofClans/bin/Release/*
        if-no-files-found: error
